version: '3.8'

services:
  node:    
    build:
      context: ./app
      dockerfile: Dockerfile
    image: node:10.14
    restart: unless-stopped
    volumes:
      - ./app:/home/node/app
    ports:
      - '3000'
    networks:
      - nginx_network
      - node-mysql-network
    command: 'npm start'
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/node.conf:/etc/nginx/conf.d/node.template
    ports:
      - '8080:80'
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
    networks:
      - nginx_network
  mysql_server:
    image: mysql:8.0
    restart: unless-stopped
    command: --init-file /data/application/init.sql
    volumes:
      - ./database/init.sql:/data/application/init.sql    
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=db_people
    networks:
      - node-mysql-network

networks:
  nginx_network:
    driver: bridge
  node-mysql-network: ~