version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/node.conf:/etc/nginx/conf.d/node.template
    ports:
      - '80:80'
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
    networks:
      - nginx_network
  node:
    image: node:10.14
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/home/node/app
    ports:
      - '3000'
    command: bash -c "npm install && npm start"
    networks:
      - nginx_network
      - node-mysql-network
  mysql_server:
    image: mysql:8.0
    command: --init-file /data/application/init.sql
    volumes:
      - ./database/init.sql:/data/application/init.sql
    restart: always
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=db_people
    networks:
      - node-mysql-network

networks:
  nginx_network:
    driver: bridge
  node-mysql-network: ~