DROP DATABASE IF EXISTS db_people;
CREATE DATABASE IF NOT EXISTS db_people;

USE db_people;

CREATE TABLE IF NOT EXISTS people (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL   
) ENGINE=INNODB;
